#!/usr/bin/env node
/**
 * Point the dashboard at the dev, staging or production Supabase project.
 *
 *   node scripts/use-env.mjs dev     → copies .env.dev     to .env.local
 *   node scripts/use-env.mjs staging → copies .env.staging to .env.local
 *   node scripts/use-env.mjs prod    → copies .env.prod    to .env.local
 *   node scripts/use-env.mjs         → says which one is active
 *
 * Run through npm: `npm run env:dev`, `npm run env:staging`, `npm run env:prod`,
 * `npm run env`, or `npm run dev` / `npm run staging` / `npm run prod` to switch
 * and start the dev server together. The same three projects, and the same
 * commands, as `scripts/use-env.mjs` in the app repo.
 *
 * ## Why copy to `.env.local` rather than load the file directly
 *
 * `.env.local` is the one file both halves of this repo read: Next loads it in
 * every mode, and the plain-Node scripts load it through `scripts/load-env.ts`.
 * Copying the chosen file there means `next dev`, `create-admin`,
 * `check:limits` and `db:types` all agree on which database they talk to.
 *
 * The files are `.env.dev` and `.env.prod`, not `.env.development` and
 * `.env.production`, on purpose: Next loads those two names by itself, by mode.
 * A `.env.production` would be picked up by every `next build` on this machine
 * whichever project was switched to.
 *
 * ## The checks
 *
 * Each file must say which environment it is (`DASHBOARD_ENVIRONMENT`), and it
 * must match the name — a `.env.prod` that quietly holds the dev project's URL
 * is how somebody "tests" a price change on the live menu. A file still holding
 * the template's placeholders is refused too.
 *
 * Vercel does not read any of this: a deployment's variables are set in the
 * Vercel project. This switches a laptop only.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const TARGET = '.env.local';

const TARGETS = {
  dev: { file: '.env.dev', environment: 'development' },
  staging: { file: '.env.staging', environment: 'staging' },
  prod: { file: '.env.prod', environment: 'production' },
};

const choice = process.argv[2];

if (!choice) {
  const current = existsSync(TARGET) ? readFileSync(TARGET, 'utf8') : '';
  const environment = value(current, 'DASHBOARD_ENVIRONMENT') ?? 'none';
  console.log(`Active: ${environment}  (${host(value(current, 'NEXT_PUBLIC_SUPABASE_URL'))})`);
  process.exit(0);
}

const target = TARGETS[choice];
if (!target) {
  fail(`Unknown environment "${choice}". Use "dev", "staging" or "prod".`);
}

if (!existsSync(target.file)) {
  fail(`${target.file} does not exist. Copy .env.example to ${target.file} and fill it in.`);
}

const contents = readFileSync(target.file, 'utf8');
const declared = value(contents, 'DASHBOARD_ENVIRONMENT');
const url = value(contents, 'NEXT_PUBLIC_SUPABASE_URL');
const anonKey = value(contents, 'NEXT_PUBLIC_SUPABASE_ANON_KEY');

if (declared !== target.environment) {
  fail(
    `${target.file} says DASHBOARD_ENVIRONMENT=${declared ?? '(unset)'}, ` +
      `but it must say ${target.environment}.`,
  );
}

if (!url || !anonKey || /<project-ref>/.test(url)) {
  fail(`${target.file} still has placeholder values. Fill in its Supabase URL and anon key first.`);
}

writeFileSync(
  TARGET,
  `# GENERATED by \`npm run env:${choice}\` from ${target.file} — edit that file, not this one.\n` +
    contents,
);

console.log(`Now using ${target.environment.toUpperCase()}  (${host(url)})`);
if (choice === 'prod') {
  console.log(
    '\n  !  This is the LIVE database. A dish, price or shop you change here is what' +
      '\n  !  customers see, and an order you touch is a real order.' +
      '\n  !  Switch back with: npm run env:dev\n',
  );
}
console.log('Restart the dev server so it picks this up (npm run dev / staging / prod do this).');

/** A variable's value from dotenv text, or null. */
function value(text, name) {
  const match = text.match(new RegExp(`^${name}=(.*)$`, 'm'));
  return match ? match[1].trim() : null;
}

/** The project's hostname — enough to tell them apart, nothing secret. */
function host(url) {
  if (!url) return 'no Supabase URL';
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}

function fail(message) {
  console.error(message);
  process.exit(1);
}
